package exception

import (
	"testing"
)

func Test_CatchError_1(t *testing.T) {}
